language: java

sudo: required

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'

script:
  - mvn test

services:
  - mysql

jdk:
  - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)