language: java

sudo: false

env:
 - TESTFOLDER=java/org.team8.webapp/DatabaseTest

 script:
  - mvn clean verify
  - "bundle exec rspec $TESTFOLDER"


jdk:
  - oraclejdk8
  - oraclejdk7

after_success:
  - bash <(curl -s https://codecov.io/bash)