language: java

sudo: required

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'
  - mysql -u root testdb < sql/dummy.sql

script:
  - mvn test

notification:
  email: false

services:
  - mysql

jdk:
  - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)