language: java

sudo: false

env:
 - TESTFOLDER=java/DatabaseTest

script:
 - mvn clean verify
 - bundle exec rspec $TESTFOLDER

jdk:
 - oraclejdk8

after_success:
 - bash <(curl -s https://codecov.io/bash)