language: java

sudo: required

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS g8_scrum_testdb;'
  - mysql -u root g8_scrum_testdb < sql/dummy.sql

script:
  - mvn test

notification:
  email: false

services:
  - mysql

jdk:
  - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)